"""add video_vision_features table

Revision ID: 33b9bfb38fd8
Revises: c931a905226f
Create Date: 2026-09-26 15:48:45.679399

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33b9bfb38fd8"
down_revision: str | Sequence[str] | None = "c931a905226f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_vision_features",
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.Column("image_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column("clip_clickbait_score", sa.Float(), nullable=True),
        sa.Column("clip_ai_generated_score", sa.Float(), nullable=True),
        sa.Column("clip_text_heavy_score", sa.Float(), nullable=True),
        sa.Column("clip_model", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_vision_features")
    # ### end Alembic commands ###
