"""add video_scores table

Revision ID: 75d8bc9ef5cf
Revises: c7d2681646c2
Create Date: 2026-09-25 20:45:26.326826

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75d8bc9ef5cf"
down_revision: str | Sequence[str] | None = "c7d2681646c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_scores",
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("predicted_label", sa.Text(), nullable=False),
        sa.Column("split", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("predicted_label IN ('up', 'down')", name="ck_video_scores_label_value"),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("video_id", "model_name", "model_version"),
    )
    op.create_index(
        "ix_video_scores_model_name_version",
        "video_scores",
        ["model_name", "model_version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_video_scores_model_name_version", table_name="video_scores")
    op.drop_table("video_scores")
    # ### end Alembic commands ###
