"""add video_nlp_features table

Revision ID: c931a905226f
Revises: 75d8bc9ef5cf
Create Date: 2026-09-26 15:32:53.791204

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c931a905226f"
down_revision: str | Sequence[str] | None = "75d8bc9ef5cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_nlp_features",
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.Column("comment_count_scored", sa.Integer(), nullable=False),
        sa.Column("sentiment_mean", sa.Float(), nullable=True),
        sa.Column("sentiment_std", sa.Float(), nullable=True),
        sa.Column("sentiment_negative_share", sa.Float(), nullable=True),
        sa.Column("slop_keyword_rate", sa.Float(), nullable=True),
        sa.Column("topic_cluster_count", sa.Integer(), nullable=True),
        sa.Column("topic_top_cluster_share", sa.Float(), nullable=True),
        sa.Column("topic_top_cluster_sentiment", sa.Float(), nullable=True),
        sa.Column("topic_sentiment_spread", sa.Float(), nullable=True),
        sa.Column("title_lure_score", sa.Float(), nullable=True),
        sa.Column("title_mysterious_score", sa.Float(), nullable=True),
        sa.Column("title_transparent_score", sa.Float(), nullable=True),
        sa.Column("title_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "description_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column(
            "comment_embedding_mean", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("sentiment_model", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_nlp_features")
    # ### end Alembic commands ###
